export const currencies = [
	{ id: "1", name: "Libra Esterlina" },
	{ id: "2", name: "Dolar Estadounidense" },
	{ id: "3", name: "Marco Alemán" },
	{ id: "4", name: "Franco Francés" },
	{ id: "5", name: "Franco Suizo" },
	{ id: "6", name: "Franco Belga" },
	{ id: "7", name: "Lira Italiana" },
	{ id: "8", name: "Florín Holandés" },
	{ id: "9", name: "Peseta (España)" },
	{ id: "10", name: "Peso Uruguayo" },
	{ id: "11", name: "Peso Chileno" },
	{ id: "12", name: "Real (Brasil)" },
	{ id: "13", name: "Chelín Austríaco" },
	{ id: "14", name: "Corona Checa" },
	{ id: "15", name: "Corona Danesa" },
	{ id: "16", name: "Escudo Portugués" },
	{ id: "17", name: "Dolar Canadiense" },
	{ id: "19", name: "Yen (Japón)" },
	{ id: "21", name: "Dolar Australiano" },
	{ id: "22", name: "Dolar Neozelandes" },
	{ id: "23", name: "Rand Sudafricano" },
	{ id: "26", name: "Nuevo Sol Peruano" },
	{ id: "27", name: "Corona Sueca" },
	{ id: "28", name: "Corona Noruega" },
	{ id: "29", name: "Dinar Serbia" },
	{ id: "31", name: "Plata - Onza Troy" },
	{ id: "32", name: "Oro - Onza Troy" },
	{ id: "33", name: "Peso Mexicano" },
	{ id: "37", name: "Marco Finlandés" },
	{ id: "38", name: "Drachma Griego" },
	{ id: "39", name: "Shekel (Israel)" },
	{ id: "40", name: "Rupia (India)" },
	{ id: "41", name: "Peso Boliviano" },
	{ id: "47", name: "Sucre Ecuatoriano" },
	{ id: "49", name: "Florín (Antillas Holande" },
	{ id: "54", name: "Peso Colombiano" },
	{ id: "69", name: "Guaraní Paraguayo" },
	{ id: "70", name: "Rublo (Rusia)" },
	{ id: "71", name: "Derecho Especial de Giro" },
	{ id: "79", name: "Bolívar Venezolano" },
	{ id: "80", name: "Peso" },
	{ id: "83", name: "Yuan - China CNY" },
	{ id: "97", name: "Ecu" },
	{ id: "98", name: "Euro" },
	{ id: "99", name: "Dolar de Singapur" },
	{ id: "300", name: "Dolar Tipo Unico" },
	{ id: "301", name: "Dolar Comercial Unico" },
	{ id: "302", name: "Dolar Financiero-Compra" },
	{ id: "303", name: "Dolar Financiero-Venta" },
	{ id: "304", name: "Dolar Finan. Esp. Compra" },
	{ id: "305", name: "Dolar Finan. Esp. Venta" },
	{ id: "306", name: "Dolar Libre (Compra)" },
	{ id: "307", name: "Dolar Libre (Venta)" },
	{ id: "308", name: "Dolar Fin.Exp.Imp. Compra" },
	{ id: "309", name: "Dolar Fin.Exp.Imp. Venta" },
	{ id: "310", name: "Dolar Oficial (Compra)" },
	{ id: "311", name: "Dolar Oficial (Venta)" },
	{ id: "312", name: "Tipo de Cambio Especial" },
	{ id: "313", name: "Dolar Referencia Com 3500" },
	{ id: "314", name: "Dolar Prom. Men. 1935/69" },
	{ id: "315", name: "Dolar Oficial Tipo Unico" },
	{ id: "316", name: "Dolar Hong Kong" },
	{ id: "317", name: "Yuan-China Off Shore CNH" },
	{ id: "318", name: "Lira Turca" },
	{ id: "319", name: "Cordoba Nicaraguense" },
	{ id: "320", name: "Dong Vietnam (c/1.000 u.)" },
] as const;